eclipse-biscuit/biscuit-haskell

biscuit-servant/test/Spec.hs
biscuit/src/Auth/Biscuit.hs
biscuit/test/Spec/Roundtrip.hs

`serializeB64` had an hex output, and `serializeHex` had a b64 output.
The fix comes with extra tests, as well as a correction in `biscuit-servant`
tests (the tests worked around the issue by using the wrong function).

Fix mixed up `serializeB64`/`serializeHex`

---

biscuit-servant/ChangeLog.md
biscuit-servant/LICENSE
biscuit-servant/README.md
biscuit-servant/biscuit-servant.cabal
biscuit/ChangeLog.md
biscuit/biscuit-haskell.cabal

biscuit-servant has not been released on hackage yet, but I'd like to keep version numbers in sync as much as possible.

Release `biscuit-haskell-0.1.1.0` with a bug fix & sync biscuit-servant

---

biscuit-servant/biscuit-servant.cabal
biscuit-servant/src/Auth/Biscuit/Servant.hs
biscuit-servant/test/AppWithVerifier.hs
biscuit-servant/test/Spec.hs

`withVerifier`, `withPriorityVerifier` and `withFallbackVerifier` now have `-M` variants, where the verifier is in a monadic context (for convenience, the same context as the handler itself). This means that the verifier context can return http errors itself. I don't expect to use this feature, but it's there. The most common uses for effectful verifiers will be:
- running `IO` to get the current time
- running `IO` plus accessing a `Reader` context to query the database

biscuit-servant: allow effectful verification

---

biscuit-servant/src/Auth/Biscuit/Servant.hs
biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Token.hs
biscuit/test/Spec/Crypto.hs

Before, it was possible to just check the signature without verifying the datalog,
but the function returned a boolean, which meant users had to ensure that the
signature was correctly checked by their own means.
This commit gives a type-safe way to separate sig check from datalog verification with
an opaque `ValidBiscuit` type.

Provide a type-safe way to separate the sig check from the datalog verif

---

biscuit/test/Spec/RevocationIds.hs
shell.nix

Now that the spec and the rust implementation support unique
revocation ids, let's make sure this implementation is consistent
with them.
The expected values have been generated using the biscuit-cli,
which uses the rust implementation.

Compliance tests for unique revocation ids

---

biscuit/src/Auth/Biscuit/Datalog/Parser.hs
biscuit/test/Spec/Parser.hs

The EBNF grammar defined in https://github.com/CleverCloud/biscuit/issues/82
makes the parsing rules a bit more explicit:
- fact names can only start with a letter

biscuit: update parser to conform to the EBNF grammar

---

biscuit/src/Auth/Biscuit/Datalog/Parser.hs

This commit makes sure that all the datalog code provided in quasiquotes
is consumed by the parser. This avoids silent failures (if a parser fails,
the input is simply not consumed and the error is silently discarded).

biscuit: don't discard errors in datalog quasiquotes

---

biscuit/app/Main.hs
biscuit/biscuit-haskell.cabal
biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Datalog/Parser.hs

This will keep dependencies aligned with the latest stackage LTS

Relax dependencies bounds and bump base16-bytestring

---

biscuit-servant/biscuit-servant.cabal
biscuit/biscuit-haskell.cabal

Version 0.2.0.0 was erroneously published with outdated code
(including outdated version bounds)

Bump version

---

biscuit/src/Auth/Biscuit/Datalog/Executor.hs
biscuit/src/Auth/Biscuit/Datalog/ScopedExecutor.hs
biscuit/test/Spec/SampleReader.hs
biscuit/test/Spec/Verification.hs

Previously, malformed rules (rules where the head had unbound variables) were
silently ignored. Now it makes evaluation fail completely, which is a safer
default (and consistent with the rust implementation).
While a rule being silently ignored is okay with `checks` and `allow` policies,
it can be dangerous if it was intended to be used with a `deny` policy

make datalog evaluation fail on malformed rule

---

biscuit/src/Auth/Biscuit/Datalog/Executor.hs
biscuit/test/Spec/SampleReader.hs
biscuit/test/Spec/Verification.hs

Now that blocks are properly scoped, it’s not needed anymore (the setting itself
was not used anymore)

datalog: remove the "allowBlockFacts" option

---

biscuit-servant/biscuit-servant.cabal
biscuit-servant/src/Auth/Biscuit/Servant.hs
biscuit-servant/test/AppWithAuthorizer.hs
biscuit-servant/test/Spec.hs
biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Datalog/ScopedExecutor.hs
biscuit/src/Auth/Biscuit/Token.hs
biscuit/test/Spec/Verification.hs

- `authHandlerWith` allows more customisation for token extraction
and error handling
- `checkBiscuitWith` and `checkBiscuitMWith` allow more customisation for error handling
- `WithAuthorizer'` allows a custom reader type parameter, along with
`withTransformation` which allows transforming an `AuthorizedBiscuit` into a custom type in a failable and effectful way.

biscuit-servant: improve flexibility

---

biscuit/biscuit-haskell.cabal

By adding the test/samples/v2 directory to the `extra-source-files` directive, we have a more conclusive archive ready for upload to hackage:
```
$ cabal sdist biscuit-haskell
/path/to/biscuit-haskell-0.2.1.0.tar.gz
$ tar --list -f /path/to/biscuit-haskell-0.2.1.0.tar.gz | grep test/samples
biscuit-haskell-0.2.1.0/test/samples/v2/
biscuit-haskell-0.2.1.0/test/samples/v2/samples.json
biscuit-haskell-0.2.1.0/test/samples/v2/test10_authorizer_scope.bc
biscuit-haskell-0.2.1.0/test/samples/v2/test11_authorizer_authority_caveats.bc
biscuit-haskell-0.2.1.0/test/samples/v2/test12_authority_caveats.bc
biscuit-haskell-0.2.1.0/test/samples/v2/test13_block_rules.bc
biscuit-haskell-0.2.1.0/test/samples/v2/test14_regex_constraint.bc
biscuit-haskell-0.2.1.0/test/samples/v2/test15_multi_queries_caveats.bc …
```

Include test files to the cabal upload

---

biscuit/src/Auth/Biscuit/Token.hs

`getRevocationIds` can be used outside of debugging in a way that makes sense (eg when registering a token revocation ids upon baking). The important part is that it should not be used when validating a token.
fixes #54

biscuit: improve documentation for `getRevocationIds`

---

biscuit-servant/test/ClientHelpers.hs
biscuit/Setup.hs
biscuit/src/Auth/Biscuit/Datalog/AST.hs
biscuit/src/Auth/Biscuit/Datalog/Executor.hs
biscuit/src/Auth/Biscuit/Datalog/Parser.hs
biscuit/src/Auth/Biscuit/Datalog/ScopedExecutor.hs
biscuit/src/Auth/Biscuit/Example.hs
biscuit/src/Auth/Biscuit/ProtoBufAdapter.hs
biscuit/test/Spec/Verification.hs

It was not possible to slice whole sets directly, on set elements. Now both elements and complete sets can be sliced in.
For convenience, sets can be sliced from any `Foldable`
```haskell
creation :: IO ByteString
creation = do
let allowedOperations = ["read", "write"] :: [Text]
networkLocal = "192.168.0.1" :: Text
let authority = [block|
// this is a comment
right("file1", ${allowedOperations});
check if source_ip($source_ip), ["127.0.0.1", ${networkLocal}].contains($source_ip);
|]
```

Allow parameter substitution for sets

---

biscuit/src/Auth/Biscuit/Datalog/Parser.hs
biscuit/test/Spec/Parser.hs

This is mostly done to provide better error messages (relaxed backtacking, explicit labels)

Parser improvements

---

biscuit-servant/README.md
biscuit-servant/src/Auth/Biscuit/Servant.hs
biscuit-servant/test/AppWithAuthorizer.hs
biscuit-servant/test/Spec.hs
biscuit/README.md
biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Datalog/AST.hs
biscuit/src/Auth/Biscuit/Datalog/Parser.hs
biscuit/src/Auth/Biscuit/Datalog/ScopedExecutor.hs
biscuit/src/Auth/Biscuit/Example.hs
biscuit/test/Spec/Parser.hs
biscuit/test/Spec/Quasiquoter.hs
biscuit/test/Spec/Roundtrip.hs
biscuit/test/Spec/ScopedExecutor.hs

Out of consistency with the rust implementation, and also to avoid confusion with datalog variables.
Since until very recently, parameters were only supported in quasi quotes, the change should be caught as a compilation error.

biscuit: change the syntax for parameters from `${name}` to `{name}`

---

.github/workflows/github-actions.yml
biscuit-servant/biscuit-servant.cabal
biscuit/biscuit-haskell.cabal
biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Datalog/AST.hs
biscuit/src/Auth/Biscuit/Datalog/Parser.hs
biscuit/src/Auth/Biscuit/Utils.hs
biscuit/test/Spec/SampleReader.hs
cabal.project

Support for GHC 9.4, 9.6 and 9.8.
This is mostly a matter of relaxing consraints. The only breaking change is in `base16` which introduced a marker type.
Interestingly enough, `Functor` is now a superclass of `Bifunctor`.

ci: test build with newer ghcs

---

.github/workflows/github-actions.yml
biscuit/src/Auth/Biscuit/Datalog/Executor.hs
biscuit/src/Auth/Biscuit/Datalog/ScopedExecutor.hs
biscuit/src/Auth/Biscuit/ProtoBufAdapter.hs
biscuit/src/Auth/Biscuit/Token.hs
biscuit/src/Auth/Biscuit/Utils.hs
biscuit/test/Spec/Executor.hs
biscuit/test/Spec/SampleReader.hs
biscuit/test/Spec/ScopedExecutor.hs

This behaviour has been clarified in the spec and is now enforced in the conformance suite

abort on evaluation error

---

biscuit-servant/src/Auth/Biscuit/Servant.hs
biscuit/src/Auth/Biscuit.hs
publish.sh

biscuit-haskell uses `SecretKey` as a key pair, and biscuit-servant deals with biscuits, not macaroons.

doc: fix outdated references

---

biscuit/src/Auth/Biscuit.hs
biscuit/src/Auth/Biscuit/Datalog/AST.hs
biscuit/src/Auth/Biscuit/Datalog/Executor.hs
biscuit/src/Auth/Biscuit/Proto.hs
biscuit/src/Auth/Biscuit/ProtoBufAdapter.hs
biscuit/src/Auth/Biscuit/Timer.hs
biscuit/src/Auth/Biscuit/Token.hs
biscuit/src/Auth/Biscuit/Utils.hs

biscuit-haskell is licensed under BSD-3-Clause, not MIT

fix: use correct license identifier in file headers

---

Makefile
biscuit-wai/ChangeLog.md
biscuit-wai/LICENSE
biscuit-wai/Setup.hs
biscuit-wai/biscuit-wai.cabal
biscuit-wai/src/Network/Wai/Middleware/Biscuit.hs
biscuit-wai/test/Spec.hs
cabal.project

While [biscuit-servant](https://hackage.haskell.org/package/biscuit-servant-0.3.0.0) provides biscuit support in servant, not everybody uses servant (shocking, I know).
This middleware is based on the same ideas:
- token extraction & parsing can be done for all endpoints in the same way
- actual authorization usually has per-endpoint logic / depends on data extracted during routing, so will usually happen outside middleware
- in some cases, authorization logic will be the same everywhere, so dedicated support should be provided to run the whole authorization process in a middleware.
Default configuration for both middlewares use the same error type, out of simplicity. it means that the default error type has an `AuthorizationError` branch even though it's not possible to reach it when …

Provide a WAI middleware 

---

CONTRIBUTING.md
README.md
biscuit-servant/ChangeLog.md
biscuit-servant/README.md
biscuit-wai/README.md
biscuit/ChangeLog.md
biscuit/README.md
biscuit/biscuit-haskell.cabal
biscuit/src/Auth/Biscuit/Proto.hs
biscuit/src/Auth/Biscuit/ProtoBufAdapter.hs

- cleanup protobuf mapper (follows https://github.com/eclipse-biscuit/biscuit/pull/182)
- update readmes & changelogs
- add `CONTRIBUTING.md`
- remove unneeded test dependency

Cleanup and documentation
